---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.19.1
    helm:
      valueFiles:
      - $values/values/cert-manager.yaml
  - repoURL: 'https://github.com/dawidde/argocd-values.git'
    targetRevision: HEAD
    path: base/kubernetes/cert-manager
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
    - CreateNamespace=true