---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://github.com/dawidde/kustomize-overlays'
    path: apps/cert-manager/overlays/prod
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
    - CreateNamespace=true