---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: external-secrets-operator
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://github.com/dawidde/kustomize-overlays'
    path: apps/external-secrets-operator/overlays/prod
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true